//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobiseStudio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobiseStudio.Resources.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to database. Make sure the data input is corret and try again..
        /// </summary>
        internal static string ConnectionFailedError {
            get {
                return ResourceManager.GetString("ConnectionFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You connected succesfuly to the data store..
        /// </summary>
        internal static string ConnectionSucess {
            get {
                return ResourceManager.GetString("ConnectionSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current project cannot be NULL..
        /// </summary>
        internal static string CurrentProjectNull {
            get {
                return ResourceManager.GetString("CurrentProjectNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creatin the database..
        /// </summary>
        internal static string DatabaseCreationError {
            get {
                return ResourceManager.GetString("DatabaseCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database was created successfully..
        /// </summary>
        internal static string DatabaseCreationSucess {
            get {
                return ResourceManager.GetString("DatabaseCreationSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default attributes cannot be changed or deleted!.
        /// </summary>
        internal static string DefaultAttributeChanges {
            get {
                return ResourceManager.GetString("DefaultAttributeChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected attribute?.
        /// </summary>
        internal static string DeleteAttributeWarning {
            get {
                return ResourceManager.GetString("DeleteAttributeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected entity?.
        /// </summary>
        internal static string DeleteEntityWarning {
            get {
                return ResourceManager.GetString("DeleteEntityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected lookup table?.
        /// </summary>
        internal static string DeleteLookupTableWarning {
            get {
                return ResourceManager.GetString("DeleteLookupTableWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected relationship?.
        /// </summary>
        internal static string DeleteRelationshipWarning {
            get {
                return ResourceManager.GetString("DeleteRelationshipWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ouput directory already exists. Please check the directory name or choose another location..
        /// </summary>
        internal static string DirectoryAlreadyExists {
            get {
                return ResourceManager.GetString("DirectoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute&apos;s name cannot be empty. Please enter a valid name..
        /// </summary>
        internal static string EmptyAttributeName {
            get {
                return ResourceManager.GetString("EmptyAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity&apos;s name cannot be empty. Please enter a valid name..
        /// </summary>
        internal static string EmptyEntityName {
            get {
                return ResourceManager.GetString("EmptyEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lookup table&apos;s name cannot be empty. Please enter a valid name..
        /// </summary>
        internal static string EmptyLookupTableName {
            get {
                return ResourceManager.GetString("EmptyLookupTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relationship&apos;s name cannot be empty. Please enter a valid name..
        /// </summary>
        internal static string EmptyRelationshipName {
            get {
                return ResourceManager.GetString("EmptyRelationshipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when trying to alter the table {0}, Do you want to force a table update (The process will drop and create the table) ?.
        /// </summary>
        internal static string ErrorAlteringTable {
            get {
                return ResourceManager.GetString("ErrorAlteringTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while copying the database to the project folder. Please try again later..
        /// </summary>
        internal static string ErrorCopyingDatabase {
            get {
                return ResourceManager.GetString("ErrorCopyingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while trying to delete the file from disk. Please try again later..
        /// </summary>
        internal static string ErrorDeletingFile {
            get {
                return ResourceManager.GetString("ErrorDeletingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while trying to delete the folder from disk. Please try again later..
        /// </summary>
        internal static string ErrorDeletingFolder {
            get {
                return ResourceManager.GetString("ErrorDeletingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not possible save the model {0} because none or more than one entity has been marked as root..
        /// </summary>
        internal static string ErrorEntityRoot {
            get {
                return ResourceManager.GetString("ErrorEntityRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another entity model with that name. Please choose a different name..
        /// </summary>
        internal static string ErrorExistingModel {
            get {
                return ResourceManager.GetString("ErrorExistingModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another screen definition or custom control with that name. Please choose a different name..
        /// </summary>
        internal static string ErrorExistingScreenDefinitionOrCustomControl {
            get {
                return ResourceManager.GetString("ErrorExistingScreenDefinitionOrCustomControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following entities have one ore more attributes that are undefined. Please select an attribute type for each of those attributes. \nEntities: {1}..
        /// </summary>
        internal static string ErrorMoreAttributesUndefined {
            get {
                return ResourceManager.GetString("ErrorMoreAttributesUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following entities have one ore more relationships that have no destination. Please select a destination for each of those relationships. \nEntities: {1}..
        /// </summary>
        internal static string ErrorMoreRelationshipsNoDestination {
            get {
                return ResourceManager.GetString("ErrorMoreRelationshipsNoDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity &apos;{0}&apos; has one ore more attributes that are undefined. Please select an attribute type for each of those attributes..
        /// </summary>
        internal static string ErrorOneAttributeUndefined {
            get {
                return ResourceManager.GetString("ErrorOneAttributeUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity &apos;{0}&apos; has one ore more relationships that have no destination. Please select a destination for each of those relationships..
        /// </summary>
        internal static string ErrorOneRelationshipNoDestination {
            get {
                return ResourceManager.GetString("ErrorOneRelationshipNoDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t set this entity as root because the entity {0} is already marked as root..
        /// </summary>
        internal static string ErrorPreviousEntityRoot {
            get {
                return ResourceManager.GetString("ErrorPreviousEntityRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while reading the file. Please check if the file is valid..
        /// </summary>
        internal static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while validating the regular expression. Please check the expression and try again..
        /// </summary>
        internal static string ErrorRegEx {
            get {
                return ResourceManager.GetString("ErrorRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file can&apos;t be removed because it is part of the current Mapping. You will need to remove the Mapping FolderModel..
        /// </summary>
        internal static string ErrorRemoveMappingFolder {
            get {
                return ResourceManager.GetString("ErrorRemoveMappingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while saving the file. Please try again later..
        /// </summary>
        internal static string ErrorSavingFile {
            get {
                return ResourceManager.GetString("ErrorSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while saving the model. Please try again later..
        /// </summary>
        internal static string ErrorSavingModel {
            get {
                return ResourceManager.GetString("ErrorSavingModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while saving the file. Please try again later..
        /// </summary>
        internal static string ErrorSavingUIDesigner {
            get {
                return ResourceManager.GetString("ErrorSavingUIDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Summary.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a folder in that location with that name. Please change the location or choose another name..
        /// </summary>
        internal static string ExistingFolder {
            get {
                return ResourceManager.GetString("ExistingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export was completed succesfully..
        /// </summary>
        internal static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was successfully saved..
        /// </summary>
        internal static string FileSaved {
            get {
                return ResourceManager.GetString("FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the models were successfully saved..
        /// </summary>
        internal static string FilesSaved {
            get {
                return ResourceManager.GetString("FilesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import successfully..
        /// </summary>
        internal static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute&apos;s name must start with a lowercase letter. Please enter a valid name..
        /// </summary>
        internal static string InvalidAttributeName {
            get {
                return ResourceManager.GetString("InvalidAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity&apos;s name must start with an uppercase letter. Please enter a valid name..
        /// </summary>
        internal static string InvalidEntityName {
            get {
                return ResourceManager.GetString("InvalidEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relationship&apos;s name must start with a lowercase letter. Please enter a valid name..
        /// </summary>
        internal static string InvalidRelationshipName {
            get {
                return ResourceManager.GetString("InvalidRelationshipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected lookup table is being used by one or more attributes, so it cannot be deleted..
        /// </summary>
        internal static string LookupTableBeenUsed {
            get {
                return ResourceManager.GetString("LookupTableBeenUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the {0} lookup table data store..
        /// </summary>
        internal static string LookupTableConectionError {
            get {
                return ResourceManager.GetString("LookupTableConectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the lookup table, the key, the item and the description. At least one of them is missing..
        /// </summary>
        internal static string LookupTableNeededFields {
            get {
                return ResourceManager.GetString("LookupTableNeededFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lookup key and the item cannot have the same value. Please change one of them..
        /// </summary>
        internal static string LookupTableSameValues {
            get {
                return ResourceManager.GetString("LookupTableSameValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Min value cannot be higher than the Max value..
        /// </summary>
        internal static string MinValueLessThanMaxValue {
            get {
                return ResourceManager.GetString("MinValueLessThanMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name you entered, is already being used by another attribute. Please use another name..
        /// </summary>
        internal static string NameBeenUsedAttribute {
            get {
                return ResourceManager.GetString("NameBeenUsedAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name you entered is already being used by another entity. Please use another name..
        /// </summary>
        internal static string NameBeenUsedEntity {
            get {
                return ResourceManager.GetString("NameBeenUsedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name you entered, is already being used by another relationship. Please use another name..
        /// </summary>
        internal static string NameBeenUsedRelationship {
            get {
                return ResourceManager.GetString("NameBeenUsedRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to create a new file? Note: All previous changes will be lost..
        /// </summary>
        internal static string NewFileWarning {
            get {
                return ResourceManager.GetString("NewFileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need write a name for the database..
        /// </summary>
        internal static string NoDatabaseNameError {
            get {
                return ResourceManager.GetString("NoDatabaseNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a database file to create a lookup table. Please select a SQLite file..
        /// </summary>
        internal static string NoDatabaseSelected {
            get {
                return ResourceManager.GetString("NoDatabaseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current model contains no entities to sync. Add Some entities and try again..
        /// </summary>
        internal static string NoEntitiesToSyncSchema {
            get {
                return ResourceManager.GetString("NoEntitiesToSyncSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to input a valid password..
        /// </summary>
        internal static string NoPasswordError {
            get {
                return ResourceManager.GetString("NoPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity {0} does not contains a primary key. The relationships associated with it cannot be created..
        /// </summary>
        internal static string NotRelationsNeedPK {
            get {
                return ResourceManager.GetString("NotRelationsNeedPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; already exists in the project. Do you want to override it?.
        /// </summary>
        internal static string OverrideFileWarning {
            get {
                return ResourceManager.GetString("OverrideFileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected project cannot be opened. Please check the project file..
        /// </summary>
        internal static string ProjectCannotBeOpened {
            get {
                return ResourceManager.GetString("ProjectCannotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t use that name because is a reserved word. Please enter a valid name..
        /// </summary>
        internal static string ReservedWordUsed {
            get {
                return ResourceManager.GetString("ReservedWordUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sync process of the database schema failed..
        /// </summary>
        internal static string SyncSchameFailedError {
            get {
                return ResourceManager.GetString("SyncSchameFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sync process of the database finished succesfully..
        /// </summary>
        internal static string SyncSchameSuccess {
            get {
                return ResourceManager.GetString("SyncSchameSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
