//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDesigner_XML {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFDesigner_XML.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VsTemplate Designer.
        /// </summary>
        public static string ErrorMessageBoxTitle {
            get {
                return ResourceManager.GetString("ErrorMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string FieldNameDescription {
            get {
                return ResourceManager.GetString("FieldNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string FieldNameId {
            get {
                return ResourceManager.GetString("FieldNameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vstemplate file you are attempting to load is missing TemplateData.
        /// </summary>
        public static string InvalidVsTemplateData {
            get {
                return ResourceManager.GetString("InvalidVsTemplateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBSync Win.
        /// </summary>
        public static string MBSyncWin {
            get {
                return ResourceManager.GetString("MBSyncWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Destination.
        /// </summary>
        public static string NoDestination {
            get {
                return ResourceManager.GetString("NoDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Inverse.
        /// </summary>
        public static string NoInverse {
            get {
                return ResourceManager.GetString("NoInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Win.
        /// </summary>
        public static string ProductionWin {
            get {
                return ResourceManager.GetString("ProductionWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reformat.
        /// </summary>
        public static string ReformatBuffer {
            get {
                return ResourceManager.GetString("ReformatBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Both Directions.
        /// </summary>
        public static string SyncBothDirections {
            get {
                return ResourceManager.GetString("SyncBothDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize XML file with view.
        /// </summary>
        public static string SynchronizeBuffer {
            get {
                return ResourceManager.GetString("SynchronizeBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync to Device Only.
        /// </summary>
        public static string SyncToDevice {
            get {
                return ResourceManager.GetString("SyncToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync to Middle Tier Only.
        /// </summary>
        public static string SyncToMiddleTier {
            get {
                return ResourceManager.GetString("SyncToMiddleTier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {1} characters or less..
        /// </summary>
        public static string ValidationFieldMaxLength {
            get {
                return ResourceManager.GetString("ValidationFieldMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a required value..
        /// </summary>
        public static string ValidationRequiredField {
            get {
                return ResourceManager.GetString("ValidationRequiredField", resourceCulture);
            }
        }
    }
}
